services:

    # Contao frontend module Respinar\ContaoLinksBundle\Controller\FrontendModule\LinkListingController
    # We used annotations for tagging the frontend module category, the frontend module type and the frontend module template
    Respinar\ContaoLinksBundle\Controller\FrontendModule\LinkListingController:
        tags:
            - { name: container.service_subscriber }
        public: true
        # Since Symfony 5 the container has to be set manually
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
    

